.\" Process this file with
.\" groff -man -Tascii zextract.1
.\"
.TH ZEXTRACT 1 "October 2016" Linux "User Manuals"
.SH NAME 
zextract \- decompress a raw zlib compressed file
.SH SYNOPSIS
.B zextract
.I [FILE...]
.SH DESCRIPTION
.B zextract
is essentially a wrapper around a clever hack to decompress raw zlib compressed files.
Using tar, zip or even gzip to uncompress such a file will fail. The actual hack prepends
the gzip header to the raw file, and then passes that entire mess into gzip, with the output
redirected into a file named after the source compressed file with ".unzipped" appended.
.SH EXAMPLE
.B zextract
foo
.RS
extracts zlib compressed file foo into a new file named foo.unzipped
.SH AUTHOR
Jared Wallace <jared-wallace@us.ibm.com>
.SH "FURTHER DETAILS"
https://w3-connections.ibm.com/blogs/sametime-linux/entry/Debugging_the_MCU_A_brief_history_of_compression?lang=en
