.\" Process this file with
.\" groff -man -Tascii zgrep.1
.\"
.TH ZGREP 1 "October 2016" Linux "User Manuals"
.SH NAME 
zgrep \- search for a string inside a raw zlib compressed file
.SH SYNOPSIS
.B zgrep
.I PATTERN
.I [FILE...]
.SH DESCRIPTION
.B zgrep
is essentially a wrapper around a clever hack to decompress raw zlib compressed files.
Using tar, zip or even gzip to uncompress such a file will fail. The actual hack prepends
the gzip header to the raw file, and then passes that entire mess into gzip, with the output
redirected into grep along with your search pattern.

You can specify an arbitrary number of zlib compressed files to grep through.
.SH AUTHOR
Jared Wallace <jared-wallace@us.ibm.com>

.SH "FURTHER DETAILS"
https://w3-connections.ibm.com/blogs/sametime-linux/entry/Debugging_the_MCU_A_brief_history_of_compression?lang=en
